"""
Synthetic cohort generator for the ResoScan healing-outcome predictor.

Pipeline (one synthetic patient at a time), grounded in `synth_params.py`:

  1. sample a demographic + injury profile from literature prevalences
  2. compute the validated clinical scores (LEG-NUI, NURD, FRACTING) exactly
  3. assign a healing archetype (normal / delayed / non-union) — biased by the
     scores, so risk factors drive outcome the way they do clinically
  4. draw the log-logistic RUST-kinematic parameters (Yinf, k, t_half)
  5. roll the trajectory forward: RUST(t) -> f1(t) (device band) -> TSI(t),
     plus the damping time-course ζ(t)
  6. emit ONLY the early-window observations (weeks 2/4/6) as model features,
     with the ground-truth outcome + weeks-to-walk as targets

Design choices that keep the data honest:
  * the outcome LABEL is derived from the rolled-out trajectory (does RUST cross
    union, and when), NOT copied from the archetype — so there is a real signal
    to learn, not a tautology.
  * vibration features (f1, SFI, ζ and their early slopes) are generated by a
    DIFFERENT physical path than the clinical scores, so an ablation can show
    they add information beyond the scores (the core thesis).

Deterministic given a seed.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional

import numpy as np

from . import synth_params as P


# --------------------------------------------------------------------------- #
#  Clinical scoring systems (exact, from the published formulas)
# --------------------------------------------------------------------------- #
def leg_nui_score(prof: dict) -> int:
    """Leeds-Genoa Non-Union Index — 8 binary factors, sum 1–8 (>=5 high risk)."""
    s = 0
    s += 1                                   # site: tibia (vs femur) always 1 here
    s += 1 if prof["open_fracture"] else 0   # soft-tissue damage / degloving
    s += 1 if prof["comminuted"] else 0      # AO type B/C (wedge/comminuted)
    s += 1 if prof["displacement_gt_75"] else 0
    s += 1 if prof["open_reduction"] else 0
    s += 1 if prof["gap_gt_4mm"] else 0
    s += 1 if not prof["optimum_stability"] else 0
    s += 1 if prof["infection"] else 0
    return int(s)


def nurd_score(prof: dict) -> int:
    """Non-Union Risk Determination score — weighted additive/subtractive, 0–21."""
    s = 0
    s += 5 if prof["flap_required"] else 0
    s += 4 if prof["compartment_syndrome"] else 0
    s += 3 if prof["chronic_condition"] else 0       # e.g. diabetes/vascular
    s += 2 if prof["open_fracture"] else 0
    s += 1 if prof["male"] else 0
    s += int(prof["asa"])                            # ASA I..IV -> 1..4
    s += int(prof["cortical_contact_grade"])         # 1..4 by contact loss
    s -= 1 if prof["spiral"] else 0
    s -= 1 if not prof["high_energy"] else 0         # low-energy subtracts 1
    return int(max(0, s))


def fracting_score(prof: dict) -> float:
    """FRACTING score — healing-time predictor, weighted multi-factor (>=8 high)."""
    s = 0.0
    age = prof["age"]
    s += 1 if age <= 45 else 2 if age <= 60 else 3
    s += 1 if prof["malnutrition"] else 0
    s += 1 if prof["diabetic"] else 0
    s += 1 if prof["smoker"] else 0
    s += 1 if prof["nsaid"] else 0
    # exposure severity
    s += 1 if not prof["open_fracture"] else (2 if prof["gustilo"] <= 2 else 3)
    s += 1 if prof["metaphyseal"] else 0
    s += 1 if prof["isolated_tibia"] else 0
    s += 1 if prof["bone_loss"] else 0
    s += 1 if prof["gap_gt_4mm"] else 0
    s += {"nail": 1, "plate": 2, "exfix": 3}[prof["device"]]
    s += 1 if not prof["optimum_stability"] else 0
    s += 1 if prof["malalignment"] else 0
    s += 1 if prof["graft_required"] else 0
    s += 1 if prof["op_time_gt_120"] else 0
    s += 1 if prof["hb_low"] else 0
    return float(s)


# --------------------------------------------------------------------------- #
#  Demographic / injury profile sampling
# --------------------------------------------------------------------------- #
def _sample_profile(rng: np.random.RandomState) -> dict:
    """Draw one patient profile from literature prevalences (with correlations)."""
    male = rng.random() < P.PREVALENCE["male"]
    age = int(np.clip(rng.normal(42, 16), 18, 85))
    smoker = rng.random() < P.PREVALENCE["smoker"]
    diabetic = rng.random() < P.PREVALENCE["diabetic"]
    high_energy = rng.random() < P.PREVALENCE["high_energy"]
    # open fractures correlate with high-energy trauma
    open_p = P.PREVALENCE["open_fracture"] * (1.6 if high_energy else 0.6)
    open_fracture = rng.random() < min(0.9, open_p)
    gustilo = int(rng.choice([1, 2, 3], p=[0.45, 0.35, 0.20])) if open_fracture else 0
    comminuted = rng.random() < (P.PREVALENCE["comminuted"] * (1.5 if high_energy else 0.7))
    gap = rng.random() < (P.PREVALENCE["gap_gt_4mm"] * (1.7 if comminuted else 0.8))
    infection = rng.random() < (P.PREVALENCE["infection"] * (2.0 if open_fracture else 0.5))

    return {
        "age": age, "male": male, "smoker": smoker, "diabetic": diabetic,
        "bmi": float(np.clip(rng.normal(25.5, 4.0), 16, 45)),
        "high_energy": high_energy, "open_fracture": open_fracture,
        "gustilo": gustilo, "comminuted": comminuted, "gap_gt_4mm": gap,
        "infection": infection,
        "displacement_gt_75": rng.random() < (0.35 if high_energy else 0.15),
        "open_reduction": rng.random() < (0.6 if comminuted else 0.3),
        "optimum_stability": rng.random() < (0.55 if not comminuted else 0.35),
        "flap_required": open_fracture and gustilo == 3 and rng.random() < 0.5,
        "compartment_syndrome": high_energy and rng.random() < 0.08,
        "chronic_condition": diabetic or (rng.random() < 0.10),
        # most patients are ASA I–II with good cortical contact → low baseline NURD
        "asa": int(rng.choice([1, 2, 3, 4], p=[0.45, 0.40, 0.13, 0.02])),
        "cortical_contact_grade": int(rng.choice([1, 2, 3, 4], p=[0.66, 0.21, 0.10, 0.03])),
        "spiral": rng.random() < 0.20 and not comminuted,
        "malnutrition": rng.random() < 0.12,
        "nsaid": rng.random() < 0.25,
        "metaphyseal": rng.random() < 0.30,
        "isolated_tibia": rng.random() < 0.40,
        "bone_loss": open_fracture and rng.random() < 0.25,
        "device": str(rng.choice(["nail", "plate", "exfix"], p=[0.6, 0.25, 0.15])),
        "malalignment": rng.random() < 0.15,
        "graft_required": rng.random() < (0.3 if gap else 0.08),
        "op_time_gt_120": rng.random() < (0.4 if comminuted else 0.2),
        "hb_low": rng.random() < 0.18,
    }


def _nurd_band_risk(nurd: int) -> float:
    """Published NURD non-union risk by score band [NURD]: 0-5→2%, 6-8→22%,
    9-11→42%, >=12→61%."""
    for cut, risk in P.NURD_RISK_BANDS:
        if nurd <= cut:
            return risk
    return P.NURD_RISK_BANDS[-1][1]


def _assign_outcome(prof: dict, leg: int, nurd: int, frac: float,
                    rng: np.random.RandomState) -> str:
    """Latent healing archetype with the validated scores carrying their REAL
    predictive power. Non-union probability is anchored to NURD's published risk
    bands and raised when LEG-NUI flags high risk (PPV 75–100%); FRACTING drives
    the delayed-union probability. This makes clinical-only prediction genuinely
    informative (as in the literature), leaving honest headroom for the vibration
    telemetry to add incremental value rather than do all the work."""
    p_non = _nurd_band_risk(nurd)                      # published NURD risk
    if leg >= P.LEG_NUI_HIGH_RISK:                     # LEG-NUI high-risk (strong PPV)
        p_non = max(p_non, 0.48)
    p_del = 0.24 if frac >= P.FRACTING_HIGH_RISK else 0.13 if frac >= 6 else 0.06
    p_del = min(p_del, max(0.0, 1.0 - p_non))
    p_nor = max(0.0, 1.0 - p_non - p_del)
    return str(rng.choice(["normal", "delayed", "nonunion"], p=[p_nor, p_del, p_non]))


# --------------------------------------------------------------------------- #
#  Physical trajectory roll-out
# --------------------------------------------------------------------------- #
def _shape(week: float, k: float, t_half: float) -> float:
    """Log-logistic healing progress 0->1 (t in weeks) [JBJS Healing Odyssey]."""
    return 1.0 / (1.0 + (max(week, 1e-3) / t_half) ** (-k))


def _zeta_at(week: float, floor: float, decay: float) -> float:
    """Damping time-course: high at fresh callus, decays (or stays high in non-union).
    `floor` and `decay` are drawn per-patient so archetypes overlap realistically."""
    return floor + (P.ZETA_FRESH - floor) * np.exp(-decay * week)


@dataclass
class Sample:
    features: dict
    outcome: str            # normal | delayed | nonunion
    weeks_to_walk: float    # weeks until TSI crosses safe-to-walk (capped)


def _make_one(rng: np.random.RandomState) -> Sample:
    prof = _sample_profile(rng)
    leg = leg_nui_score(prof)
    nurd = nurd_score(prof)
    frac = fracting_score(prof)
    arch = _assign_outcome(prof, leg, nurd, frac, rng)

    # archetype trajectory parameters (frequency-centric, device band)
    f_fresh = rng.normal(*P.F_FRESH_FRAC)
    f_plateau = rng.normal(*P.F_PLATEAU[arch])
    k = max(0.20, rng.normal(*P.SHAPE_K[arch]))
    t_half = max(3.0, rng.normal(*P.SHAPE_THALF_WK[arch]))
    Yinf = rng.normal(*P.LOGLOG[arch]["Yinf"])             # RUST asymptote (radiographic)
    f_healthy = rng.normal(P.F_HEALTHY_HZ, P.F_HEALTHY_SD)
    f_safe = P.TSI_SAFE_TO_WALK / 100.0 * f_healthy        # f at linear-TSI 80
    # per-patient damping parameters (drawn around the archetype baseline)
    zeta_floor = rng.normal(P.ZETA_FLOOR[arch], P.ZETA_FLOOR_SD)
    zeta_decay = max(0.01, rng.normal(P.ZETA_DECAY_PER_WEEK[arch], 0.03))

    def f_at(wk: float) -> float:
        return f_fresh + (f_plateau - f_fresh) * _shape(wk, k, t_half)

    # roll trajectory forward for the continuous target (weeks-to-walk)
    weeks_to_walk = 52.0
    for wk in np.arange(2, 53, 0.5):
        if f_at(wk) >= f_safe:
            weeks_to_walk = float(wk)
            break

    # GROUND-TRUTH label = the latent biological archetype. This is NOT a function
    # of the observed early frequency, so predicting it from early vibration is a
    # real (non-circular) task: both the clinical scores and the vibration channel
    # are imperfect early observers of this latent fate.
    outcome = arch

    # ---- early-window OBSERVED features (weeks 2/4/6 only) ----
    f_series, sfi_series, zeta_series, rust_series = [], [], [], []
    f0 = None
    for wk in P.OBSERVED_WEEKS:
        prog = _shape(wk, k, t_half)
        f = f_at(wk) + rng.normal(0, P.F_SIGMA_HZ)
        if f0 is None:
            f0 = max(1.0, f)
        sfi = (f * f - f0 * f0) / (f0 * f0) * 100.0     # squared frequency increment %
        z = _zeta_at(wk, zeta_floor, zeta_decay) + rng.normal(0, P.ZETA_SIGMA)
        # RUST is a RADIOGRAPHIC (X-ray) score with real inter-observer variability —
        # NOT something our device measures. It belongs to the clinical/standard-care
        # block, and is deliberately noisy so it stays a realistic ~75% predictor.
        rust = P.RUST_Y0 + (Yinf - P.RUST_Y0) * prog + rng.normal(0, P.RUST_OBS_SD)
        rust = float(np.clip(round(rust), 4, 12))
        f_series.append(f); sfi_series.append(sfi)
        zeta_series.append(z); rust_series.append(rust)

    # slopes over the early window (per week)
    def _slope(ys):
        xs = np.array(P.OBSERVED_WEEKS, float)
        return float(np.polyfit(xs, ys, 1)[0])

    features = {
        # --- demographics / injury (clinical block) ---
        "age": prof["age"], "male": int(prof["male"]), "bmi": round(prof["bmi"], 1),
        "smoker": int(prof["smoker"]), "diabetic": int(prof["diabetic"]),
        "open_fracture": int(prof["open_fracture"]), "gustilo": prof["gustilo"],
        "comminuted": int(prof["comminuted"]), "gap_gt_4mm": int(prof["gap_gt_4mm"]),
        "infection": int(prof["infection"]), "high_energy": int(prof["high_energy"]),
        "asa": prof["asa"],
        # --- validated clinical scores (clinical block) ---
        "leg_nui": leg, "nurd": nurd, "fracting": round(frac, 1),
        # --- vibration telemetry (the novel block) ---
        "f1_wk6": round(f_series[-1], 1),
        "f1_slope": round(_slope(f_series), 2),
        "sfi_wk6": round(sfi_series[-1], 2),
        "sfi_slope": round(_slope(sfi_series), 2),
        "zeta_wk6": round(zeta_series[-1], 4),
        "zeta_slope": round(_slope(zeta_series), 4),
        "rust_wk6": round(rust_series[-1], 2),
    }
    return Sample(features=features, outcome=outcome, weeks_to_walk=weeks_to_walk)


# --------------------------------------------------------------------------- #
#  Public API
# --------------------------------------------------------------------------- #
# Which feature columns belong to which block (used by the ablation in train.py).
# CLINICAL = everything standard care has WITHOUT our device, including the
# radiographic 6-week RUST score (an X-ray). VIBRATION = our device's signal only
# (radiation-free): resonant frequency, squared-frequency-increment, damping.
CLINICAL_FEATURES = [
    "age", "male", "bmi", "smoker", "diabetic", "open_fracture", "gustilo",
    "comminuted", "gap_gt_4mm", "infection", "high_energy", "asa",
    "leg_nui", "nurd", "fracting", "rust_wk6",
]
VIBRATION_FEATURES = [
    "f1_wk6", "f1_slope", "sfi_wk6", "sfi_slope", "zeta_wk6", "zeta_slope",
]
ALL_FEATURES = CLINICAL_FEATURES + VIBRATION_FEATURES
OUTCOME_LABELS = ["normal", "delayed", "nonunion"]


def generate_cohort(n: int = 5000, seed: int = 20260608):
    """Generate a synthetic cohort. Returns (X, y_class, y_weeks, feature_names)."""
    rng = np.random.RandomState(seed)
    rows, y_class, y_weeks = [], [], []
    for _ in range(n):
        s = _make_one(rng)
        rows.append([s.features[k] for k in ALL_FEATURES])
        y_class.append(OUTCOME_LABELS.index(s.outcome))
        y_weeks.append(s.weeks_to_walk)
    return (np.array(rows, float), np.array(y_class, int),
            np.array(y_weeks, float), list(ALL_FEATURES))


if __name__ == "__main__":  # quick sanity check
    X, yc, yw, names = generate_cohort(2000, seed=1)
    import collections
    dist = collections.Counter(OUTCOME_LABELS[i] for i in yc)
    print(f"cohort: {len(X)} patients, {len(names)} features")
    print("outcome mix:", dict(dist))
    print("weeks-to-walk: mean %.1f  median %.1f  capped(52) %d"
          % (yw.mean(), np.median(yw), int((yw >= 52).sum())))
