"use client";

/**
 * Model view — the early healing-outcome predictor and its honest evidence.
 *
 * Leads with the ABLATION (the thesis: radiation-free vibration beats standard
 * radiographic care, and fusion beats both). All detailed metrics live in
 * collapsible dropdowns so they can be revealed on demand during the demo.
 *
 * Data: web/lib/healing-metrics.json (generated by backend/ml_research/train.py).
 */

import { useState } from "react";
import {
  ShieldCheck, Activity, GraduationCap, Sparkles, ChevronDown, Radio, Stethoscope, Layers,
} from "lucide-react";
import metrics from "@/lib/healing-metrics.json";
import { InfoTip } from "@/components/ui/info-tip";

type Arm = { n_features: number; f1_macro_mean: number; f1_macro_std: number; accuracy_mean: number };
type PerClass = Record<string, { precision: number; recall: number; f1: number; support: number }>;
type Healing = {
  model: string; data: string; n_patients: number; n_features: number;
  outcome_mix: Record<string, number>;
  ablation: { clinical_only: Arm; vibration_only: Arm; fused: Arm };
  vibration_lift_macro_f1: number;
  classification_holdout: {
    accuracy: number; macro_f1: number; per_class: PerClass;
    confusion_matrix: number[][]; labels: string[];
  };
  regression_holdout: { weeks_to_walk_mae: number; r2: number; note: string };
  top_features: { feature: string; importance: number }[];
  honesty_note: string;
};
const M = metrics as unknown as Healing;

const pct = (x: number) => `${(x * 100).toFixed(1)}%`;
const FEATURE_LABELS: Record<string, string> = {
  f1_slope: "Frequency rise rate (f₁ slope)", zeta_wk6: "Damping at week 6 (ζ)",
  f1_wk6: "Frequency at week 6", rust_wk6: "X-ray RUST score (week 6)",
  leg_nui: "LEG-NUI score", nurd: "NURD score", fracting: "FRACTING score",
  sfi_wk6: "Squared-frequency increment", sfi_slope: "SFI rise rate",
  zeta_slope: "Damping decay rate", age: "Age", smoker: "Smoking", diabetic: "Diabetes",
  gap_gt_4mm: "Fracture gap >4mm", open_fracture: "Open fracture", gustilo: "Gustilo grade",
  comminuted: "Comminuted", infection: "Infection", high_energy: "High-energy", asa: "ASA grade",
  bmi: "BMI", male: "Male",
};
const isVibration = (f: string) =>
  ["f1_slope", "zeta_wk6", "f1_wk6", "sfi_wk6", "sfi_slope", "zeta_slope"].includes(f);

export function ModelView() {
  const abl = M.ablation;
  const lift = M.vibration_lift_macro_f1;

  return (
    <div className="flex flex-col gap-6 p-6">

      {/* Header */}
      <header>
        <div className="flex items-center gap-2">
          <ShieldCheck size={15} className="text-accent" strokeWidth={1.7} />
          <span className="font-display text-base font-semibold text-text">
            Early Healing-Outcome Predictor
          </span>
          <InfoTip k="accuracy" side="bottom" />
        </div>
        <p className="mt-0.5 text-[12px] text-text-muted">
          Predicts Normal / Delayed / Non-union from the first 6 weeks · {M.n_patients.toLocaleString()} synthetic cases · {M.n_features} features
        </p>
      </header>

      {/* ── THE HEADLINE: ablation ── */}
      <div className="surface p-5" style={{ borderColor: "rgba(0,255,170,0.25)" }}>
        <div className="mb-1 flex items-center gap-1.5 text-[11px] uppercase tracking-[0.16em] text-text-faint">
          Does the device add value beyond standard care? <InfoTip title="Ablation" plain="We train the same model on three feature sets and compare. If the vibration device beats the clinical + X-ray baseline, it's measuring something new." side="bottom" />
        </div>
        <p className="mb-4 text-[13px] leading-relaxed text-text-muted">
          We trained the identical model on three inputs. The result is the whole thesis:
          our <span className="font-semibold" style={{ color: "var(--accent)" }}>radiation-free vibration
          device alone beats the clinical + X-ray baseline</span> — and fusing both is best.
        </p>

        <div className="flex flex-col gap-3">
          <AblationBar label="Clinical + X-ray (standard care)" icon={Stethoscope}
            value={abl.clinical_only.f1_macro_mean} acc={abl.clinical_only.accuracy_mean}
            n={abl.clinical_only.n_features} color="var(--text-muted)" />
          <AblationBar label="Vibration device only · radiation-free" icon={Radio}
            value={abl.vibration_only.f1_macro_mean} acc={abl.vibration_only.accuracy_mean}
            n={abl.vibration_only.n_features} color="var(--caution)" highlight />
          <AblationBar label="Fused (ResoScan)" icon={Layers}
            value={abl.fused.f1_macro_mean} acc={abl.fused.accuracy_mean}
            n={abl.fused.n_features} color="var(--accent)" highlight />
        </div>

        <div className="mt-4 flex items-center gap-2 rounded-lg border border-line px-3 py-2"
          style={{ background: "rgba(0,255,170,0.05)" }}>
          <Sparkles size={14} className="text-accent shrink-0" />
          <span className="text-[12.5px] text-text-muted">
            Vibration lifts prediction by <span className="font-semibold text-text">+{lift.toFixed(2)} macro-F1</span> over
            the clinical scores — without any radiation. <em>That's what the device measures that an X-ray can't see early.</em>
          </span>
        </div>
      </div>

      {/* ── Hero stats ── */}
      <section className="grid grid-cols-2 gap-3 md:grid-cols-4">
        <Hero icon={ShieldCheck} label="Fused accuracy" value={pct(M.classification_holdout.accuracy)}
          sub="3-class holdout" tip="accuracy" />
        <Hero icon={Radio} label="Vibration lift" value={`+${lift.toFixed(2)}`}
          sub="macro-F1 vs clinical" />
        <Hero icon={Activity} label="Weeks-to-walk error" value={`±${M.regression_holdout.weeks_to_walk_mae.toFixed(1)}`}
          sub={`weeks · R² ${M.regression_holdout.r2.toFixed(2)}`} />
        <Hero icon={GraduationCap} label="Training cases" value={M.n_patients.toLocaleString()}
          sub="literature-grounded synthetic" />
      </section>

      {/* ── Collapsible detail (reveal on demand) ── */}
      <div className="flex flex-col gap-3">
        <Dropdown title="Outcome accuracy by class" subtitle="precision · recall · F1 + confusion matrix">
          <PerClassBlock />
        </Dropdown>

        <Dropdown title="What the AI looks at" subtitle="feature importances — vibration leads">
          <FeatureBlock />
        </Dropdown>

        <Dropdown title="The ablation in detail" subtitle="three feature sets, 5-fold cross-validated">
          <AblationDetail />
        </Dropdown>

        <Dropdown title="Methodology & honesty" subtitle="what's synthetic, what's grounded, what's pending">
          <p className="text-[13px] leading-relaxed text-text-muted">{M.honesty_note}</p>
          <div className="mt-3 grid grid-cols-1 gap-2 sm:grid-cols-3 text-[11px]">
            <Tag tone="ok" label="Grounded in literature" detail="every parameter cited (Tower, Mattei, LEG-NUI, NURD, FRACTING, JBJS)" />
            <Tag tone="warn" label="Synthetic training data" detail="no public vibration dataset exists; real-patient validation is next" />
            <Tag tone="warn" label="RUST→frequency is a modelling bridge" detail="labelled assumption, not measured" />
          </div>
        </Dropdown>
      </div>
    </div>
  );
}

// ── ablation bar ──────────────────────────────────────────────────────────────
function AblationBar({ label, icon: Icon, value, acc, n, color, highlight }: {
  label: string; icon: React.ComponentType<{ size?: number; className?: string }>;
  value: number; acc: number; n: number; color: string; highlight?: boolean;
}) {
  return (
    <div>
      <div className="mb-1 flex items-center justify-between text-[12px]">
        <span className="flex items-center gap-1.5" style={{ color: highlight ? color : "var(--text-muted)" }}>
          <Icon size={12} /> {label}
        </span>
        <span className="font-mono text-text-muted">
          F1 <span className="font-semibold" style={{ color }}>{value.toFixed(2)}</span> · {pct(acc)} · {n}f
        </span>
      </div>
      <div className="h-3 w-full overflow-hidden rounded-full bg-bg-panel">
        <div className="h-full rounded-full transition-all"
          style={{ width: `${value * 100}%`, background: color, opacity: highlight ? 1 : 0.55 }} />
      </div>
    </div>
  );
}

// ── hero ──────────────────────────────────────────────────────────────────────
function Hero({ icon: Icon, label, value, sub, tip }: {
  icon: React.ComponentType<{ size?: number; strokeWidth?: number; className?: string }>;
  label: string; value: string; sub: string; tip?: string;
}) {
  return (
    <div className="surface flex flex-col gap-2 p-5">
      <div className="flex items-center justify-between">
        <span className="flex items-center gap-1 text-[10px] uppercase tracking-[0.16em] text-text-faint">
          {label} {tip && <InfoTip k={tip} side="bottom" />}
        </span>
        <Icon size={14} strokeWidth={1.6} className="text-accent" />
      </div>
      <div className="mt-1 font-mono text-[30px] font-semibold leading-none text-text">{value}</div>
      <p className="text-[11px] leading-snug text-text-muted">{sub}</p>
    </div>
  );
}

// ── collapsible dropdown ──────────────────────────────────────────────────────
function Dropdown({ title, subtitle, children }: {
  title: string; subtitle?: string; children: React.ReactNode;
}) {
  const [open, setOpen] = useState(false);
  return (
    <div className="surface overflow-hidden">
      <button onClick={() => setOpen((v) => !v)}
        className="flex w-full items-center justify-between px-5 py-3.5 text-left transition-colors hover:bg-bg-card">
        <div>
          <div className="text-[13px] font-semibold text-text">{title}</div>
          {subtitle && <div className="text-[11px] text-text-muted">{subtitle}</div>}
        </div>
        <ChevronDown size={16} className="text-text-muted transition-transform"
          style={{ transform: open ? "rotate(180deg)" : "none" }} />
      </button>
      {open && <div className="border-t border-line px-5 py-4">{children}</div>}
    </div>
  );
}

// ── per-class + confusion matrix ──────────────────────────────────────────────
function PerClassBlock() {
  const labels = M.classification_holdout.labels;
  const pc = M.classification_holdout.per_class;
  const cm = M.classification_holdout.confusion_matrix;
  const weakest = Object.entries(pc).sort((a, b) => a[1].f1 - b[1].f1)[0];
  return (
    <div className="grid grid-cols-1 gap-5 lg:grid-cols-[minmax(0,1fr)_auto]">
      <div>
        <table className="w-full text-[12px]">
          <thead>
            <tr className="border-b border-line text-left text-[10px] uppercase tracking-wide text-text-faint">
              <th className="py-2 font-medium">Outcome</th>
              <th className="py-2 font-medium text-right"><span className="inline-flex items-center gap-1">Precision <InfoTip k="precision" side="bottom" /></span></th>
              <th className="py-2 font-medium text-right"><span className="inline-flex items-center gap-1">Recall <InfoTip k="recall" side="bottom" /></span></th>
              <th className="py-2 font-medium text-right"><span className="inline-flex items-center gap-1">F1 <InfoTip k="f1" side="bottom" /></span></th>
              <th className="py-2 font-medium text-right">Cases</th>
            </tr>
          </thead>
          <tbody className="font-mono">
            {labels.map((l) => {
              const r = pc[l]; if (!r) return null;
              const weak = l === weakest[0];
              return (
                <tr key={l} className="border-b border-line/50">
                  <td className="py-2 font-sans capitalize text-text" style={weak ? { color: "var(--caution)" } : undefined}>{l}</td>
                  <td className="py-2 text-right text-text-muted">{pct(r.precision)}</td>
                  <td className="py-2 text-right text-text-muted">{pct(r.recall)}</td>
                  <td className="py-2 text-right font-semibold"
                    style={{ color: r.f1 >= 0.85 ? "var(--safe)" : r.f1 >= 0.6 ? "var(--accent)" : "var(--caution)" }}>{r.f1.toFixed(2)}</td>
                  <td className="py-2 text-right text-text-faint">{r.support}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
        <p className="mt-2 text-[11px] text-text-faint">
          Weakest class: <span className="capitalize text-text-muted">{weakest[0]}</span> (F1 {weakest[1].f1.toFixed(2)}) —
          borderline healing cases are genuinely hard; we report it honestly.
        </p>
      </div>
      <div>
        <div className="mb-2 flex items-center gap-1.5 text-[10px] uppercase tracking-wide text-text-faint">
          Confusion matrix <InfoTip k="confusionMatrix" side="bottom" />
        </div>
        <ConfusionMatrix labels={labels} cm={cm} />
      </div>
    </div>
  );
}

function ConfusionMatrix({ labels, cm }: { labels: string[]; cm: number[][] }) {
  const max = Math.max(...cm.flat());
  const short = (l: string) => l.slice(0, 3).toUpperCase();
  return (
    <table className="border-collapse">
      <thead>
        <tr><th className="p-1" />{labels.map((l) => (
          <th key={l} className="p-1 font-mono text-[10px] text-text-faint" title={l}>{short(l)}</th>
        ))}</tr>
      </thead>
      <tbody>
        {cm.map((row, i) => (
          <tr key={i}>
            <td className="p-1 pr-2 text-right font-mono text-[10px] text-text-faint" title={labels[i]}>{short(labels[i])}</td>
            {row.map((v, j) => {
              const diag = i === j; const it = max ? v / max : 0;
              return (
                <td key={j} className="p-0.5">
                  <div className="flex h-10 w-10 items-center justify-center rounded font-mono text-[12px]"
                    style={{
                      background: diag ? `rgba(0,255,170,${0.12 + it * 0.5})` : v > 0 ? `rgba(255,180,50,${0.1 + it * 0.4})` : "rgba(255,255,255,0.03)",
                      color: diag ? "var(--accent)" : v > 0 ? "var(--caution)" : "var(--text-faint)",
                    }}>{v}</div>
                </td>
              );
            })}
          </tr>
        ))}
      </tbody>
    </table>
  );
}

// ── feature importances ───────────────────────────────────────────────────────
function FeatureBlock() {
  const feats = M.top_features.slice(0, 8);
  const max = Math.max(...feats.map((f) => f.importance));
  return (
    <div className="flex flex-col gap-2">
      {feats.map((f) => {
        const vib = isVibration(f.feature);
        return (
          <div key={f.feature} className="flex items-center gap-3">
            <span className="w-48 shrink-0 text-[12px] text-text-muted">
              {FEATURE_LABELS[f.feature] ?? f.feature}
              {vib && <span className="ml-1 text-[9px] uppercase" style={{ color: "var(--accent)" }}>vib</span>}
            </span>
            <div className="h-2.5 flex-1 overflow-hidden rounded-full bg-bg-panel">
              <div className="h-full rounded-full"
                style={{ width: `${(f.importance / max) * 100}%`, background: vib ? "var(--accent)" : "var(--text-muted)" }} />
            </div>
            <span className="w-10 text-right font-mono text-[11px] text-text-faint">{(f.importance * 100).toFixed(0)}%</span>
          </div>
        );
      })}
      <p className="mt-1 text-[11px] text-text-faint">
        <span style={{ color: "var(--accent)" }}>Cyan = vibration</span> (device) features lead — the rate of
        frequency rise and the damping are the strongest signals, matching the literature's most-sensitive early indicators.
      </p>
    </div>
  );
}

// ── ablation detail ───────────────────────────────────────────────────────────
function AblationDetail() {
  const rows: [string, Arm][] = [
    ["Clinical + X-ray (standard care)", M.ablation.clinical_only],
    ["Vibration device only (radiation-free)", M.ablation.vibration_only],
    ["Fused (ResoScan)", M.ablation.fused],
  ];
  return (
    <table className="w-full text-[12px]">
      <thead>
        <tr className="border-b border-line text-left text-[10px] uppercase tracking-wide text-text-faint">
          <th className="py-2 font-medium">Feature set</th>
          <th className="py-2 font-medium text-right">Features</th>
          <th className="py-2 font-medium text-right">Macro-F1</th>
          <th className="py-2 font-medium text-right">Accuracy</th>
        </tr>
      </thead>
      <tbody className="font-mono">
        {rows.map(([name, a]) => (
          <tr key={name} className="border-b border-line/50">
            <td className="py-2 font-sans text-text">{name}</td>
            <td className="py-2 text-right text-text-faint">{a.n_features}</td>
            <td className="py-2 text-right font-semibold text-text">{a.f1_macro_mean.toFixed(3)} <span className="text-text-faint">±{a.f1_macro_std.toFixed(3)}</span></td>
            <td className="py-2 text-right text-text-muted">{pct(a.accuracy_mean)}</td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}

function Tag({ tone, label, detail }: { tone: "ok" | "warn"; label: string; detail: string }) {
  const c = tone === "ok" ? "var(--safe)" : "var(--caution)";
  return (
    <div className="rounded-lg border border-line px-3 py-2" style={{ borderColor: `${c}33` }}>
      <div className="text-[11px] font-semibold" style={{ color: c }}>{label}</div>
      <div className="mt-0.5 text-[10.5px] leading-snug text-text-muted">{detail}</div>
    </div>
  );
}
